on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: echo "Workflow triggered successfully!"

